# Generated by Django 4.0.3 on 2023-05-02 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jobs.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_tile', models.CharField(blank=True, max_length=144, null=True)),
                ('qualification', models.CharField(blank=True, max_length=144, null=True)),
                ('focus_areas', models.CharField(blank=True, max_length=144, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('no_open_positions', models.IntegerField(blank=True, null=True)),
                ('no_of_applicants', models.IntegerField(blank=True, null=True)),
                ('max_no_of_applicant', models.IntegerField(blank=True, null=True)),
                ('last_submission_date', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('posting_client', models.ForeignKey(default=jobs.models.get_default_client, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-post_time',),
            },
        ),
        migrations.CreateModel(
            name='JobApplicationTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_title', models.CharField(blank=True, max_length=144, null=True)),
                ('status', models.CharField(blank=True, max_length=144, null=True)),
                ('invited_for_interview', models.BooleanField(default=False)),
                ('applied_by', models.ForeignKey(default=jobs.models.get_default_applicant, on_delete=django.db.models.deletion.SET_DEFAULT, to='bot_users.applicantprofile')),
                ('applied_to', models.ForeignKey(default=jobs.models.get_default_client, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('job_listing', models.ForeignKey(default=jobs.models.get_default_job_listing, on_delete=django.db.models.deletion.SET_DEFAULT, to='jobs.joblistings')),
            ],
            options={
                'ordering': ('-applied_at',),
            },
        ),
    ]
